### ISSUE TITLE
Multiple lines in textareas show as one line

### ISSUE THREAD

**Issue by hashworks** [ProjectFirrre/zncstrap#17]
![example](http://i.imgur.com/6kRdtkq.png)

This is present in the master branch as well in the dev branch.

BTW, this problem doesn't exist in the original themes for server lists, but for fingerprints:
![original](http://i.imgur.com/efeQ9m3.png)

**Comment by sprybear** [comment]
Hi there, hashworks,

Thank you for reporting it. It should be fixed now, corrected the CSS bit. I've updated both branches for v1.4 (master) and v1.6 (dev) and higher. You will only have to replace '../webskins/_defaults_/pub/_default_.css'. Give it a try.

**Comment by hashworks** [comment]
Thanks for the quick fix, sadly it's not fixed for me:
![screenshot](http://i.imgur.com/sYoGOtS.png)
As you see the fingerprints are fucked up as well, they show up as one fingerprint (joined by `:` )

I also tried re-saving the servers & fingerprints, now they're correct in the config but stil messed up in the webadmin interface:

```
Server = irc.rizon.net +9999
Server = irc.rizon.no +9999
Server = irc.shakeababy.net +9999
Server = irc.lolipower.org +9999
Server = irc.cccp-project.net +9999
Server = irc.broke-it.com +9999
Server = irc.cyberdynesystems.net +9999
Server = irc.rizon.io +9999
Server = irc.rizon.us +9999
Server = irc.rizon.sexy +9999
Server = irc.sxci.net +9999
Server = irc.ku.cx +9999
Server = irc.losslessone.com +9999
Server = irc.x2x.cc +9999
Server = irc.blackened.org +9999
Server = irc.rizon.so +9999
Server = irc.uworld.se +9999
Server = irc.infoqb.se +9999
Server = irc.vmnode.pw +9999
TrustedServerFingerprint = 2f:3f:ae:02:43:8d:c1:e6:af:4f:0b:d5:4d:7d:5a:32:57:1c:f9:3c:4f:8b:1c:2d:dc:ee:a1:9b:32:0c:7f:e7
TrustedServerFingerprint = 4a:11:29:1e:30:72:52:99:b0:f8:54:26:f9:63:78:b7:2d:00:bb:3b:7e:16:40:f5:95:d4:31:74:d0:0a:93:f5
TrustedServerFingerprint = b7:fe:9c:2d:16:03:3c:77:0c:91:5a:b5:6b:bd:74:f7:c9:cf:7b:12:47:36:63:92:5b:6d:1e:12:c7:d8:b2:ee
TrustedServerFingerprint = b8:d8:e0:c3:b4:e1:69:8d:b0:1e:e1:ca:bf:38:1d:c2:23:63:96:ac:6d:0b:96:ed:65:cf:2f:8b:47:0c:a8:21
TrustedServerFingerprint = de:56:17:a5:34:1c:f5:cd:aa:f7:cf:c2:d9:2c:a6:47:f6:23:a3:33:72:51:bb:68:a3:21:4b:11:96:85:0c:7c
TrustedServerFingerprint = ea:e5:58:50:ae:2a:ce:2c:05:7a:d3:30:c2:1e:35:c7:fd:4e:a5:2d:31:20:c0:10:97:9d:78:5a:04:40:22:44
TrustedServerFingerprint = fd:e0:68:4b:1c:07:d8:bb:d8:6c:bd:42:8e:c9:1a:ef:f0:0c:4f:85:e2:d3:00:e7:ed:2f:8a:ea:79:ab:52:5e
```

**Comment by Cajs** [comment]
I have the same issue.

**Comment by Hobby-boy** [comment]
I have the exact same problem with a plain ZNC 1.6.0 install, with both the master and dev branches, before and after the fix. 
Same with a ZNC 1.2 install on Ubuntu 14.04

**Comment by sprybear** [comment]
Roger that. Will revisit this.

**Comment by t3chguy** [comment]
I too have this issue

**Comment by sprybear** [comment]
Update: Working on it. This issue should be fixed in the next release (fingers-crossed) within 2 - 3 days time. There are some new additions made to ZNC v1.7-git; I'm working on that bit too.

Hang in there, cowboys/girls ;)
